### ISSUE TITLE
Possible it decrease minimum python version?

### ISSUE THREAD

**Issue by theFestest** [susumuota/nanoatp#11]
I've noticed that the pinned python version is somewhat specific. This prevented me from deploying this code as a dependency to a Serverless function in vercel.

Vercel has a runtime for "3.9" but they do not specify the bugfix release versions. Using "^3.9.0" instead of "^3.9.16" might resolve this.

**Comment by susumuota** [comment]
@theFestest Thanks! I fixed Python version to "^3.9".
